# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Street.create(street: 'бульв.Б.Хмельницкого')
Street.create(street: 'бульв.Грицевца')
Street.create(street: 'бульв.Юрьева')
Street.create(street: 'въезд Тринклера')
Street.create(street: '﻿Белгородское шоссе')
Street.create(street: 'Карачаевское шоссе')
Street.create(street: 'Комсомольское шоссе')
Street.create(street: 'Красношкольная набережная')
Street.create(street: 'Нетеченская набережная')
Street.create(street: 'Харьковская набережная')
Street.create(street: 'пер.Армянский')
Street.create(street: 'пер.Банный')
Street.create(street: 'пер.Плетневский')
Street.create(street: 'пер.Спартаковский')
Street.create(street: 'пл.1-го Мая')
Street.create(street: 'пл.Благовещенская')
Street.create(street: 'пл.Бугримовой')
Street.create(street: 'пл.Конституции')
Street.create(street: 'пл.Павловская')
Street.create(street: 'пл.Пролетарская')
Street.create(street: 'пл.Руднева')
Street.create(street: 'пл.Рыбная')
Street.create(street: 'пл.Свободы')
Street.create(street: 'пр-зд.Садовый')
Street.create(street: 'пр-кт.50-летия ВЛКСМ')
Street.create(street: 'пр-кт.50-летия СССР')
Street.create(street: 'пр-кт.Гагарина')
Street.create(street: 'пр-кт.Героев Сталинграда')
Street.create(street: 'пр-кт.Жукова')
Street.create(street: 'пр-кт.Ильича')
Street.create(street: 'пр-кт.Косиора')
Street.create(street: 'пр-кт.Ленина')
Street.create(street: 'пр-кт.М.Жукова')
Street.create(street: 'пр-кт.Московский')
Street.create(street: 'пр-кт.Орджоникидзе')
Street.create(street: 'пр-кт.Победы')
Street.create(street: 'пр-кт.Постышева')
Street.create(street: 'пр-кт.Правды')
Street.create(street: 'пр-кт.Тракторостроителей')
Street.create(street: 'пр-кт.Фрунзе')
Street.create(street: 'пр-кт.Л.Свободы')
Street.create(street: 'пр-кт.Ак.Курчатова')
Street.create(street: 'Салтовское шоссе')
Street.create(street: 'спуск Жильярди')
Street.create(street: 'ул.1-й Конной Армии')
Street.create(street: 'ул.2-й Пятилетки')
Street.create(street: 'ул.23-Августа')
Street.create(street: 'ул.3-го Интернационала')
Street.create(street: 'ул.17-го Партсъезда')
Street.create(street: 'ул.Ак.Богомольца')
Street.create(street: 'ул.Ак.Павлова')
Street.create(street: 'ул.Ак.Павлова')
Street.create(street: 'ул.Ак.Проскуры')
Street.create(street: 'ул.Артема')
Street.create(street: 'ул.Архитекторов')
Street.create(street: 'ул.Ахсарова')
Street.create(street: 'ул.Аэрофлотская')
Street.create(street: 'ул.Б.Акации')
Street.create(street: 'ул.Б.Гончаровская')
Street.create(street: 'ул.Балакирева')
Street.create(street: 'ул.Барабашова')
Street.create(street: 'ул.Блюхера')
Street.create(street: 'ул.Богомольца')
Street.create(street: 'ул.Большая Кольцевая')
Street.create(street: 'ул.Валдайская')
Street.create(street: 'ул.Велозаводская')
Street.create(street: 'ул.Вернадского')
Street.create(street: 'ул.Веснина')
Street.create(street: 'ул.Володарского')
Street.create(street: 'ул.Гамарника')
Street.create(street: 'ул.Гарибальди')
Street.create(street: 'ул.Гв.Широнинцев')
Street.create(street: 'ул.Героев Труда')
Street.create(street: 'ул.Герцена')
Street.create(street: 'ул.Грековская')
Street.create(street: 'ул.Грицевца')
Street.create(street: 'ул.Деревянко')
Street.create(street: 'ул.Державинская')
Street.create(street: 'ул.Динамовская')
Street.create(street: 'ул.Др.Народов')
Street.create(street: 'ул.Елизарова')
Street.create(street: 'ул.Зерновая')
Street.create(street: 'ул.Золочевская')
Street.create(street: 'ул.Зубарева')
Street.create(street: 'ул.И.Камышева')
Street.create(street: 'ул.Иванова')
Street.create(street: 'ул.Ильинская')
Street.create(street: 'ул.Искринская')
Street.create(street: 'ул.К.Корка')
Street.create(street: 'ул.Карла Маркса')
Street.create(street: 'ул.Катаева')
Street.create(street: 'ул.Каштановая')
Street.create(street: 'ул.Клочковская')
Street.create(street: 'ул.Конева')
Street.create(street: 'ул.Кооперативная')
Street.create(street: 'ул.Корчагинцев')
Street.create(street: 'ул.Космическая')
Street.create(street: 'ул.Костычева')
Street.create(street: 'ул.Котлова')
Street.create(street: 'ул.Коцарская')
Street.create(street: 'ул.Красноармейская')
Street.create(street: 'ул.Краснодарская')
Street.create(street: 'ул.Краснооктябрьская')
Street.create(street: 'ул.Л.Пастера')
Street.create(street: 'ул.Ленинградская')
Street.create(street: 'ул.Марьинская')
Street.create(street: 'ул.Матюшенко')
Street.create(street: 'ул.Медицинская')
Street.create(street: 'ул.Менжинского')
Street.create(street: 'ул.Механизаторская')
Street.create(street: 'ул.Мироносицкая')
Street.create(street: 'ул.Морозова')
Street.create(street: 'ул.Муранова')
Street.create(street: 'ул.Нариманова')
Street.create(street: 'ул.Новгородская')
Street.create(street: 'ул.Новый Быт')
Street.create(street: 'ул.Ньютона')
Street.create(street: 'ул.О.Яроша')
Street.create(street: 'ул.Октябрьской революции')
Street.create(street: 'ул.Олимпийская')
Street.create(street: 'ул.Ощепкова')
Street.create(street: 'ул.Парижской Комунны')
Street.create(street: 'ул.Петровского')
Street.create(street: 'ул.Плехановская')
Street.create(street: 'ул.Плиточная')
Street.create(street: 'ул.Полтавский шлях')
Street.create(street: 'ул.Пушкинская')
Street.create(street: 'ул.Революции 1905')
Street.create(street: 'ул.Роганская')
Street.create(street: 'ул.Рымарская')
Street.create(street: 'ул.Рязанская')
Street.create(street: 'ул.Светлая')
Street.create(street: 'ул.Слинько')
Street.create(street: 'ул.Совнаркомовская')
Street.create(street: 'ул.Соича')
Street.create(street: 'ул.Социалистическая')
Street.create(street: 'ул.Среднеуральская')
Street.create(street: 'ул.Сумская')
Street.create(street: 'ул.Тимирязева')
Street.create(street: 'ул.Уборевича')
Street.create(street: 'ул.Университетская')
Street.create(street: 'ул.Хабарова')
Street.create(street: 'ул.Халтурина')
Street.create(street: 'ул.Харьковских Дивизий')
Street.create(street: 'ул.Целиноградская')
Street.create(street: 'ул.Цюрупы')
Street.create(street: 'ул.Чебышева')
Street.create(street: 'ул.Чернышнвская')
Street.create(street: 'ул.Чкалова')
Street.create(street: 'ул.Чугуевская')
Street.create(street: 'ул.Шевченко')
Street.create(street: 'ул.Якира')

#=====================================

Line.create(name: '1.1', view: '1_1.gif', describe: "Разделяет транспортные 
  потоки противоположных направлений и обозначает границы полос движения 
  на дорогах; обозначает границы проезжей части, на которые въезд запрещен; 
  обозначает границы мест стоянки транспортных средств, 
  площадок для парковки и край проезжей части дорог, 
  не отнесенных по условиям движения к автомагистралям.")
Line.create(name: '1.3', view: '1_3.gif', describe:"Разделяет транспортные потоки противоположных направлений на дорогах, 
  имеющих четыре и более полосы движения.")
Line.create(name: '1.5', view: '1_5.gif', describe:"Разделяет транспортные потоки противоположных направлений на дорогах, имеющих две или три полосы; обозначает границы полос движения при наличии двух и более полос, 
  предназначенных для движения в одном направлении.")
Line.create(name: '1.6', view: '1_6.gif', describe:"Предупреждает о приближении к разметке 1.1 или 1.11, которая разделяет 
  транспортные потоки противоположных или попутных направлений.")
Line.create(name: '1.12', view: '1_12.gif', describe:"Обозначает место, где водитель должен остановиться при наличии знака 2.2
  либо при сигнале светофора или регулировщика, запрещающем движение.")
Line.create(name: '1.14.1', view: '1_14_1.gif', describe:"Обозначает нерегулируемый пешеходный переход.")
Line.create(name: '1.14.2', view: '1_14_2.gif', describe:"Обозначает пешеходный переход, движение по которому регулируется светофором.")
Line.create(name: '1.14.3', view: '1_14_3.gif', describe:"Обозначает нерегулируемый пешеходный переход с повышенной опасностью возникновения дорожно-транспортных происшествий.")
Line.create(name: '1.7', view: '1_7.gif', describe:"Обозначает полосы движения, а также направление главной дороги в пределах перекрестка.")
Line.create(name: '1.8', view: '1_8.gif', describe:"Обозначает границу между переходно-скоростной полосой разгона или торможения и основной полосой проезжей части (на перекрестках, пересечениях дорог на разных уровнях, в зоне автобусных остановок и т. п.)")
Line.create(name: '1.13', view: '1_13.gif', describe:"Обозначает место, где водитель должен при необходимости остановиться и уступить дорогу транспортным средствам, движущимся по пересекаемой дороге.")
Line.create(name: '1.16', view: '1_16.gif', describe:"Обозначает направляющие островки в местах разделения, разветвления или слияния транспортных потоков.")
Line.create(name: '1.18', view: '1_18.gif', describe:"Показывает разрешенные на перекрестке на­правления движения по полоса.")
Line.create(name: '2.6', view: '2_6.gif', describe:"Бордюры направляющего островка и островка безопасности.")